apiVersion: v1
kind: ConfigMap
metadata:
  name: microbench-configmap
data:
  microbench.sh: |
    #!/bin/bash
    set -x

    #yum -y update
    #yum -y install gcc git
    #yum -y groupinstall "Development Tools"
    #yum -y install gcc git make
    apt-get update
    apt-get install -y build-essential git
    gcc --version
    git clone https://github.com/handong32/peakler.git
    cd peakler/experiments/microbenchmarks
    COUNT=5000000 make build/runALU
    nproc
    sleep 60
    echo "3"
    sleep 1
    echo "2"
    sleep 1
    echo "1"
    sleep 1
    taskset -c 1 ./build/runALU 65000
    sleep 60