apiVersion: v1
kind: ConfigMap
metadata:
  name: microbench-configmap
data:
  microbench.sh: |
    #!/bin/bash
    set -x

    dnf -y update
    dnf -y groupinstall "Development Tools"
    
    echo "游릭游릭 Checking GCC/G++  游릭游릭"
    gcc --version
    g++ --version

    echo "游릭游릭 Building microbenchmarks  游릭游릭"
    
    git clone https://github.com/handong32/peakler.git    
    cd peakler/experiments/microbenchmarks
    COUNT=5000000 make build/runALU

    nproc

    for (( i=1; i<=3; i++ )); do
        echo "游릭游릭 ITER ${i}: runALU 27000  游릭游릭"
        for (( s=10; s>0; s-- )); do
            echo "游릭 WAIT ${s} 游릭"
            sleep 1
        done
        taskset -c 87 ./build/runALU 27000
        for (( s=10; s>0; s-- )); do
            echo "游릭 WAIT${s} 游릭"
            sleep 1
        done
    done
    
    #echo "游릭游릭 runALU 27000  游릭游릭"
    #sleep 60
    #taskset -c 87 ./build/runALU 27000
    #sleep 60

    

