# Use the latest Ubuntu image as base
FROM ubuntu:latest

# Update package lists and install gcc and git
RUN apt-get update && \	   
    apt-get install -y gcc git && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Run the binary and output it to a file
CMD gcc --version