apiVersion: batch/v1
kind: Job
metadata:
  name: microbench
spec:
  template:
    spec:
      containers:
        - name: microb
          image: ubuntu
          command: ["/script/microbench.sh"]
          volumeMounts:
            - name: script
              mountPath: "/script"
      volumes:
        - name: script
          configMap:
            name: microbench-configmap
            defaultMode: 0500
      restartPolicy: Never