apiVersion: batch/v1
kind: Job
metadata:
  name: microbench-pcm
spec:
  template:
    spec:
      containers:
        - name: microb-pcm
          image: quay.io/centos/centos:stream8
          command: ["/script/microbench.sh"]
          volumeMounts:
            - name: script
              mountPath: "/script"
      volumes:
        - name: script
          configMap:
            name: microbench-configmap-pcm
            defaultMode: 0500
      restartPolicy: Never