apiVersion: batch/v1
kind: Job
metadata:
  name: microbench-test
spec:
  template:
    spec:
      containers:
        - name: microb
          image: quay.io/centos/centos:stream8
          securityContext:
            privileged: true
          command: ["/script/microbench.sh"]
          volumeMounts:
            - name: script
              mountPath: "/script"
      volumes:
        - name: script
          configMap:
            name: microbench-configmap-test
            defaultMode: 0500
      restartPolicy: Never
      hostNetwork: true